### PR TITLE
Documentation: Acceleration registers are read-only + remove one TODO comment

### PR DESCRIPTION
**Pull request by gudnimg**

### CODE REVIEW

**Review by 3d-gussner — APPROVED** [review]
Thanks for updating the documentation

**Comment by 3d-gussner** [comment]
@DRracer Looking at https://github.com/prusa3d/Prusa-Firmware-MMU/issues/333 would it make sense to allow to write these registers? Then This PR need to be changed.

**Comment by DRracer** [comment]
Yes, with the latest optimization PRs from @gudnimg : #328 #335 #336 
we'll have 500B+ free, so implementing the accelerations should fit now.

@gudnimg are up to the challenge :wink: ?

**Comment by gudnimg** [comment]
> Yes, with the latest optimization PRs from @gudnimg : #328 #335 #336 we'll have 500B+ free, so implementing the accelerations should fit now.
> 
> @gudnimg are up to the challenge 😉 ?

Can't promise it right now 😄 I will take a look at the code to get a better idea of how much work is needed.

I suspect the major thing to solve in this feature is how to handle changing the motor settings at any time. Perhaps we can use the infrastructure we already use for changing Stealth mode.

**Comment by gudnimg** [comment]
Created https://github.com/prusa3d/Prusa-Firmware-MMU/pull/337 I don't think it is more complex than this 👀

**Review by 3d-gussner — APPROVED** [review]

**Comment by gudnimg** [comment]
Closing in favor of https://github.com/prusa3d/Prusa-Firmware-MMU/pull/341

**Pull request closed without merging**
